### ISSUE TITLE
Adopt layout from https://github.com/fulldecent/swift5-module-template

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/FDChessboardView#18]
A modern project layout for Swift modules is defined at https://github.com/fulldecent/swift5-module-template

# Work plan

- [ ] Study best practices at link above
- [ ] Apply the "Recipe" from the Swift 5 Module Template to this project
- [ ] Ensure that PR does not change the current development team
- [ ] Convert PNGs to Swift (because Swift Package Manager does not support resources yet), see example in the Recipe
- [ ] Add support for CocoaPods

# Follow-on work

- [ ] Make a minor version feature release with this updated project

**Comment by fulldecent** [comment]
All done and made release
